# Oh-my-zsh
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="nipeko"
plugins=(git )

unsetopt correct_all

source $ZSH/oh-my-zsh.sh
source $HOME/.env

# Git aliases
alias g="git"
alias gst="git status"
alias gcam="git commit -am"
alias gp="git push"
alias gcm="git checkout master"

alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

alias md='mkdir -p'
alias rd=rmdir
alias d='dirs -v | head -10'

# List directory contents
alias lsa='ls -lah'
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -lAh'

alias q="nix-env -qaP --description '.*' | grep -i"
alias nv='nvim $HOME/nixos-config/configuration.nix'
alias zs='source $HOME/.zshrc'
alias zv='nvim $HOME/.zshrc'
alias xv='nvim $HOME/.xmonad/xmonad.hs'
